spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/web_store_test?useSSL=false
    password: add your passeword

  mail:
    host: smtp.gmail.com
    port: 587
    username: add sender email
    password: app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084


