spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/web_store_test?useSSL=false
    password: 32902344

  mail:
    host: smtp.gmail.com
    port: 587
    username: anuradhawickramasingha98@gmail.com
    password: ifbl eetb oqsf vabc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084


